### ISSUE TITLE
Cannot install motus due to missing dependency 'maptools'

### ISSUE THREAD

**Issue by pepijn-devries** [MotusWTS/motus#21]
Thanks for your work on this package!

Note that 'maptools' is imported by the 'motus' package, but is no longer available from CRAN. Therefore, I cannot install motus as described in the documentation. In order to make it work, I have to manually install an archived version of maptools like so:

```
devtools::install_version("maptools",version="1.1-8")
```

Could either the documentation be updated or the dependencies be fixed?

Cheers,

Pepijn

**Comment by Ewan-P** [comment]
All, thanks for everything do with this package.

I echo the comment from pepijn, though the sustainable solution is to remove the dependency on maptools.

Is this related to this discussion on  the RStudio/ POSIT forums
https://community.rstudio.com/t/retirement-of-rgeos-rgdal-maptools/134989

and this on Github
https://github.com/r-spatial/evolution

I'm not competent to work out how to fix this, but I'm happy to help with beta testing.

All the best
EAP

**Comment by mpricha** [comment]
Hello - I'm having the same issue with the maptools dependency. The archived version of maptools (thanks pepijn) worked for me for now, but I wonder if there is an update on a better fix?

**Comment by pepijn-devries** [comment]
It seems that the package `maptools`  is only used by `motus` for calculating sunset and sunrise times. Alternatively, the `suncalc` package (which is still on CRAN) can be used for that. This should fix the issue. If I have some time I could work on a pull request.

**Comment by steffilazerte** [comment]
Hi everyone, sorry for the delay in responding (I didn't have alerts on, but that's fixed now). And thanks for the heads up!

This issue has been fixed the the dev version, the release of which has been delayed due to an API issue. I am hoping to get it released ASAP and will keep you posted.

**Comment by steffilazerte** [comment]
Okay, I think the dev version is ready for release 🎉 

Are any of you able to test out the package for me?

You can install the dev version with the `remotes` package: 
```{r}
install.packages("remotes")                     # if don't already have it
remotes::install_github("motusWTS/motus@dev")
```

It should install without problems (i.e. the maptool issue). You may run into the occasional timeout issue (related to the API), but that shouldn't stop you from installing etc.

**Comment by mpricha** [comment]
@steffilazerte It seems to work for me!

**Comment by Ewan-P** [comment]
Steffi,

Pleased to report that Dev package installed  without problem and my
scripts are running as expected.

Thanks.
EAP

**Comment by steffilazerte** [comment]
Thank you everyone, motus v6.1.0 is now released :tada:! 
Let me know in new issues if you run into any new problems 🙏🏼
